name: Delete Artifacts

on:
  schedule:
    - cron: '0 0 * * 0'  # This cron expression runs the workflow every Sunday at midnight UTC
  workflow_dispatch:
    inputs:
      GITHUB_TOKEN:
        description: 'Set the area code'
        required: false  # Set as false to make it optional
        default: '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'   # Default value if not provided
        type: string
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: List and delete artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          artifacts=$(gh api -H "Authorization: token ${GITHUB_TOKEN}" repos/:owner/:repo/actions/artifacts | jq -r '.artifacts[] | select(.expired == false) | .id')
          for artifact in $artifacts; do
            gh api -H "Authorization: token ${GITHUB_TOKEN}" repos/:owner/:repo/actions/artifacts/$artifact -X DELETE
          done
